#!/bin/sh
set -e
if [ -n $1 ];
then
    PARAL=12
else
    PARAL=$1
fi

rm -rf ./build
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Debug -DTEST_ALL=yes ../
make -j ${PARAL}
make test
make install
cd ..
